### ISSUE TITLE
User Story 1: Creating Home page

### ISSUE THREAD

**Issue by JonFD4** [JonFD4/FitFlex#1]
As a user, I want to acces the homepage..
As a user, I want to browse available workout plans, so I can see what options are available.
As a user I want to easily navigate via a nav bar to see where products are, accounts detail etc ...

- [ ] Task 1.1: Set up the homepage to list all workout plans (#2)
- [ ] Task 1.2: Create a workout plan model in Django (#3)
- [ ] Task 1.3: Fetch and display workout plans on the homepage (#4)
- [x] Task 1.4: Style the homepage using Bootstrap (#5)
- [x] Task 1.5: Create navbar #35
